CREATE TABLE IF NOT EXISTS BOOKSHELF (
    ID int NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(1028),
    CREATED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(128) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_USER VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);